### ISSUE TITLE
建议丰富各种编码类型，支持检测以及exp

### ISSUE THREAD

**Issue by ymbzd** [bcvgh/daydayEXP#4]
例如nuclei中如下写法，因为是反序列解码后是乱码的，目前使用这个工具没法实现检测以及exp
![image](https://github.com/bcvgh/daydayEXP/assets/39881690/2f9d6478-d8b8-47f5-ac43-08ba0b47abee)

**Comment by bcvgh** [comment]
感谢你的建议，检测反序列化的功能现在是通过DNSURL链生成字节数组直接去请求实现的，还在测试没上线。当然，nuclei的这种写法我也会加入考虑范围。

**Comment by ymbzd** [comment]
师傅方便给个联系方式吗  还有一些问题需要反馈

**Comment by bcvgh** [comment]
> 师傅方便给个联系方式吗 还有一些问题需要反馈

bcvgh0709
